#pragma once

enum JOY_BUTTONS
{
  JOY_BUTTON_A,
  JOY_BUTTON_B,
  JOY_BUTTON_Y,
  JOY_BUTTON_X,
  JOY_BUTTON_LB,
  JOY_BUTTON_RB,
  JOY_BUTTON_LT,
  JOY_BUTTON_RT,
  JOY_BUTTON_SELECT,
  JOY_BUTTON_START,
  JOY_BUTTON_OPTIONS,
  JOY_BUTTON_LS,
  JOY_BUTTON_RS,
  JOY_BUTTON_UP,
  JOY_BUTTON_DOWN,
  JOY_BUTTON_LEFT,
  JOY_BUTTON_RIGHT
};
